run:
   uv run main.py 

clean:
    @echo "Cleaning up files..."
    @rm -f *.png *.csv *.log
    @echo "Cleaned up files."

clean_sql:
    @echo "Cleaning up database tables..."
    psql -U postgres -d postgres -f scripts/clean_table.sql
    @echo "Database tables cleaned."

