run:
    bun run dev

check:
    @echo Fixing format and lint issues
    bun run check

clean:
    @echo "Cleaning up files..."
    @rm -f *.png *.csv *.log
    @find . -maxdepth 1 -type f -name "*.json" ! -name "package.json" ! -name "biome.json" ! -name "tsconfig.json" -delete
    @echo "Cleaned up files."

clean_sql:
    @echo "Cleaning up database tables..."
    psql -U postgres -d postgres -f scripts/clean_table.sql
    @echo "Database tables cleaned."

