run:
    bun run dev

check:
    @echo Fixing format and lint issues
    bun run check

clean:
    @echo "Cleaning up files..."
    @rm -f *.png *.csv *.log
    @echo "Cleaned up files."

clean_sql:
    @echo "Cleaning up database tables..."
    psql -U postgres -d postgres -f scripts/clean_table.sql
    @echo "Database tables cleaned."

