run:
    @echo "Starting the development server..."
    bun run dev

clean:
    @echo "Cleaning up files..."
    @rm -f *.png *.csv *.log
    @echo "Cleaned up files."

clean_sql:
    @echo "Cleaning up database tables..."
    psql -U postgres -d postgres -f scripts/clean_table.sql
    @echo "Database tables cleaned."

